package com.sunilsamuel.brms.rules;

import com.sunilsamuel.brms.model.OUS;

rule "Test 1"
salience 1
activation-group "permission"
when
	$ous: OUS(organization.matches(".*"))
then
	$ous.setAccess(false);
	System.out.println("Test 1 rule: " + $ous.toString());
end

rule "Test 2"
salience 2
activation-group "permission"
when
	$ous: OUS(organization == "DHS")
then
	$ous.setAccess(true);
	System.out.println("Test 2 rule: " + $ous.toString());
end

rule "Test 3"
salience 3
activation-group "permission"
when
	$ous: OUS(organization == "DHS", unit == "FEMA")
then
	$ous.setAccess(false);
	System.out.println("Test 3 rule: " + $ous.toString());
end

